# config.yaml

database:
  name: us_visa
  collection_name: visa_data

pipeline:
  name: usvisa
  artifact_dir: artifact

files:
  train_file: train.csv
  test_file: test.csv
  raw_file: usvisa.csv
  model_file: model.pkl
  preprocessing_object_file: preprocessing.pkl

target:
  column: case_status
  current_year: 2025  # Placeholder to be updated at runtime

data_ingestion:
  collection_name: visa_data
  dir_name: data_ingestion
  feature_store_dir: feature_store
  ingested_dir: ingested
  train_test_split_ratio: 0.2
