# config.yaml
# Database related constants (start with DB var name)
database:
  name: us_visa
  collection_name: visa_data

# Pipeline related constants (start with PIPELINE var name)
pipeline:
  name: usvisa
  artifact_dir: artifact

# Data Processing related constants (start with DATA_PROCESSING var name)
files:
  train_file: train.csv
  test_file: test.csv
  raw_file: usvisa.csv
  validation_file: data_validation_artifact.yaml
  model_file: model.pkl
  preprocessing_object_file: preprocessing.pkl


# Target related constants (start with TARGET var name)
target:
  column: case_status
  current_year: 2025  # Placeholder to be updated at runtime

# Data Ingestion related constants (start with DATA_INGESTION var name)
data_ingestion:
  dir_name: data_ingestion
  feature_store_dir: feature_store
  ingested_dir: ingested
  train_test_split_ratio: 0.2

# Data Validation related constants (start with DATA_VALIDATION var name)
data_validation:
  dir_name: "data_validation"
  drift_report_dir: "drift_report"
  drift_report_file_name: "report.yaml"

# data transformation related constants
data_transformation:
  data_transformation_dir_name: "data_transformation"
  data_transformation_transformed_data_dir: "transformed"
  data_transformation_transformed_object_dir: "transformed_object"

# model trainer related constants
model_trainer:
  dir_name: model_trainer
  trained_model_dir: trained_model_object
  trained_model_name: model.pkl
  expected_score: 0.75
  model_config_file_path: model.yaml


aws:
  access_key_id: "AWS_ACCESS_KEY_ID"
  secret_access_key: "AWS_SECRET_ACCESS_KEY"
  region: "us-east-1"

model_evaluation:
  changed_threshold_score: 0.02
  bucket_name: "usvisa-model2025"
  pusher_s3_key: "model-registry"


model_pusher:
  bucket_name: "usvisa-model2025"
  pusher_s3_key: "model-registry"
